services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: starvault
      POSTGRES_PASSWORD: starvault
      POSTGRES_DB: starvault
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
