services:
  db:
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    image: postgres:17.4-alpine
    ports:
      - '5432:5432'
    restart: unless-stopped
