services:
  db:
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    image: postgres:17.4-alpine
    ports:
      - '5432:5432'
    restart: unless-stopped
  redis:
    image: redis:7.4.2-alpine
    ports:
      - '6379:6379'
    restart: unless-stopped
